[좌표 계산기] 터틀봇 미션 제출합니다.
woowacourse/java-coordinate pull request #12
Opened 2019-05-23 08:01 UTC by huisam

안녕하세요! 제이슨 리뷰어님!
3주차 미션 좌표 계산기 제출합니다!
TDD를 항상 의식해서 하니까 코드 완성해가면서 나중에 기분 좋은 안정감을 느낄 수 있어서 좋았어요
뭔가 이번 미션은 리뷰하기도 엄청 힘들 것 같은 느낌이 드네요ㅠㅠ
매주마다 시간내서 해주셔서 항상 감사드립니다 :) 💯

2019-05-28 05:13 UTC, pobiconan requested changes
포비가 대신 리뷰해요.

전체적인 객체 구조, 메소드 분리, 클린코드 구현 등 잘 했네요. 💯 
인터페이스 분리와 중복 코드 제거 등도 좋네요.

오늘 수업 중 다룬 내용에 대한 피드백 남겼으니 반영해 보세요.

2019-05-28 05:13 UTC, pobiconan commented on src/main/java/coordinatecalculator/domain/Coordinate.java
> +    private final int y;
오늘 수업 중 미션에도 있었음.
원시 값을 포장하는 원칙에 따라 구현해 본다.

2019-05-28 05:13 UTC, pobiconan commented on src/main/java/coordinatecalculator/domain/Coordinate.java
> +    private final int y;
원시 값을 포장할 경우 매번 인스턴스를 생성해야하기 때문에 성능이 떨어지는 이슈가 있다.
객체를 재사용 가능한 구조로 구현해 본다.

2019-05-28 05:13 UTC, pobiconan commented on src/main/java/coordinatecalculator/domain/Coordinate.java
> +    public double calculateSlope(final Coordinate coordinate) {
👍

2019-05-28 05:13 UTC, pobiconan commented on src/main/java/coordinatecalculator/domain/Coordinate.java
> +    public double calculateDistance(final Coordinate coordinate) {
👍

2019-05-28 05:13 UTC, pobiconan commented on src/main/java/coordinatecalculator/domain/Coordinates.java
> +        return Collections.unmodifiableList(coordinates);
👍

2019-05-28 05:13 UTC, pobiconan commented on src/main/java/coordinatecalculator/factory/ShapeType.java
> +enum ShapeType {
👍

2019-05-28 05:13 UTC, pobiconan commented on src/test/java/coordinatecalculator/domain/TriangleTest.java
> +        });
테스트 코드 구현 하는 것을 보면 한 번에 너무 여러 가지 경우를 테스트하고 있는데 각 경우의 수를 분리해 보는 것도 좋겠다.
만약 분리하지 않는다면 테스트 데이터와 실행부는 가까운 곳에 위치하도록 구현하는 것은 어떨까?

2019-05-28 06:36 UTC, merged

2019-05-29 02:15 UTC, huisam commented on src/test/java/coordinatecalculator/domain/TriangleTest.java
> +        });
확실히 분리하는 편이 다른 사람의 입장에서 읽기가 편할 것 같다는 생각이 드네요 :)
간단한 케이스라도 이해하기 쉽게 작성하는 것이 좋을 것 같습니다!