Men7627
woowacourse/java-coordinate pull request #16
Opened 2019-05-23 09:08 UTC by men7627

[좌표 계산기] 쿠기 미션 제출합니다.

2019-05-24 23:59 UTC, gracefulBrown requested changes
안녕하세요. 리뷰어 브라운입니다 :)
상속과 인터페이스 사용을 비롯한 객체 구조 설계를 잘 하셨네요 👍 
몇 가지 코멘트를 남겼으니 참고해서 구현해보면 좋을 것 같아요 ^^
궁금한 점 있으시면 편하게 DM 주세요~

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/view/InputView.java
> +        private static List<Point> makePoints(List<String> inputs) {
일급콜렉션을 사용하면 Points 관련로직을 모을 수 있을 것 같은데 사용해보는 것을 추천드립니다 :)

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/controller/Main.java
> +                        return IShape.MAPPING_SHAPE.get(points.size()).apply(points);
Shape을 생성해주는 부분을 별도의 클래스로 분리하는것은 어떨까요?

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/util/HeronFormula.java
> +public class HeronFormula {
관련된 클래스들은 같은 패키지에 있거나 가깝게 위치하는 게 좋습니다.
해당 클래스의 로직이 삼각형에서만 사용된다면 Triangle의 메소드로 위치하는 것도 고려해봐도 좋을 것 같아요

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/view/InputView.java
> +                        PointNumber x = new PointNumber(Integer.parseInt(matcher.group(1)));
PointNumber는 Point 내부에서만 사용할 수 있도록 하면 PointNumber와 Point관련 로직이 조금 더 응집도가 높아질 수 있습니다. :)

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/model/PointNumber.java
> +public class PointNumber {
"원시값을 포장한다." 👍

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/model/Triangle.java
> +                return HeronFormula.getTriangleArea(points.get(FIRST_POINT).getDistance(points.get(SECOND_POINT)),
points의 일급 컬렉션 객체가 있으면 해당 라인의 길이가 조금 줄어들 수 있겠네요ㅎㅎ
```
ex)

return HeronFormula.getTriangleArea(points.getDistance(FIRST_POINT, SECOND_POINT),
```

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/model/Point.java
> +        public double getDistance(Point anotherPoint) {
메서드의 이름을 조금 더 명확하게 할 수 있을 것 같아요 :) 
ex) getDistanceFrom

2019-05-24 23:59 UTC, gracefulBrown commented on src/main/java/coordinate/view/OutputView.java
> +        private static void drawYAxis(StringBuilder sb, int index) {
반드시 지켜야 할 룰은 아니지만 참고하면 좋을 것 같아서 코멘트 남겨요 ^^

![image](https://user-images.githubusercontent.com/46308949/58361434-be6f4400-7ec9-11e9-9092-cbcb104e32b5.png)


## 참고자료
- [Clean Code Chapter 3 : Functions > Have No Side Effects > Output Arguments ](https://books.google.co.kr/books?id=_i6bDeoCQzsC&pg=PA45&lpg=PA45&dq=to+check+the+function+signature+is+equivalent+to+a+double-take&source=bl&ots=ep7SEj2g53&sig=ACfU3U0pv6SNDXCS7UbaL12aEWjduadWeA&hl=ko&sa=X&ved=2ahUKEwioxeDZqrXiAhVD-WEKHQITBboQ6AEwAHoECAcQAQ#v=onepage&q&f=false)
- [클린코드 > 함수 관련 블로그](https://zeddios.tistory.com/420)

2019-05-27 05:24 UTC, men7627 commented on src/main/java/coordinate/util/HeronFormula.java
> +public class HeronFormula {
수정했습니다 !

2019-05-27 05:37 UTC, men7627 commented on src/main/java/coordinate/view/InputView.java
> +                        PointNumber x = new PointNumber(Integer.parseInt(matcher.group(1)));
Point 생성자에서 PointNumber를 생성하는 방식으로 수정해 해결하였습니다 !

2019-05-27 05:38 UTC, men7627 commented on src/main/java/coordinate/model/PointNumber.java
> +public class PointNumber {
감사합니다~! :)

2019-05-27 06:05 UTC, men7627 commented on src/main/java/coordinate/controller/Main.java
> +                        return IShape.MAPPING_SHAPE.get(points.size()).apply(points);
IShapeCreator 클래스를 만들어 IShape을 생성하는 로직을 IShape과 분리하였습니다 !

2019-05-27 07:34 UTC, men7627 commented on src/main/java/coordinate/view/InputView.java
> +        private static List<Point> makePoints(List<String> inputs) {
List<Point>를 일급콜렉션을 사용해 Points 클래스로 만들어 보았습니다.
그리고 InputView에 있던 makePoints를 아래 추천해주신 IShape에 대한 생성하는 부분을 분리해낸 것 처럼 PointsCreator로 분리해 보았습니다 !

2019-05-27 07:35 UTC, men7627 commented on src/main/java/coordinate/model/Triangle.java
> +                return HeronFormula.getTriangleArea(points.get(FIRST_POINT).getDistance(points.get(SECOND_POINT)),
Points의 일급 컬렉션을 사용해 길이를 줄였습니다.

2019-05-27 07:36 UTC, men7627 commented on src/main/java/coordinate/model/Point.java
> +        public double getDistance(Point anotherPoint) {
Ponts의 일급 컬렉션을 사용하니 저 메서드 자체가 필요 없어졌습니다~!

2019-05-27 09:10 UTC, men7627 commented on src/main/java/coordinate/view/OutputView.java
> +        private static void drawYAxis(StringBuilder sb, int index) {
의도하신 바가 맞는지 확신이 서진 않지만 매개변수로 StringBuilder를 주는 것을 모두 제거하는 방향으로 변경하였습니다. 아무래도 이렇게 해야 좀더 객체지향적인 것 같네요 !
그런데 인덴트도 맞추고, 메서드 라인도 맞추다 보고, 매개변수까지 제한 두다 보니 삼항 연산자를 사용하는 등 좀 더 복잡해진 감이 없지 않아 있어보이는데 피드백 부탁드립니다 !

2019-05-27 09:15 UTC, men7627 commented
이번 패드백을 통해 네가지 정도를 학습한 것 같습니다.

1. 일급 컬렉션을 통해 컬렉션을 클래스로 만들기
2. IShspeCreator, PointsCreator ( 팩토리메서드 패턴(??) 맞는지 모르겠습니다... ) 만들기
3. StringBuilder를 매개변수로 주는 것을 제거하기
4. PointNumber를 Point에서만 사용하도록 하기

이 모두 코드를 좀 더 객체지향적으로 만드데에 중요한 작업들이 었던 것 같습니다. 수정하고 보니 제가 봐도 제 코드가 좀 더 객체가 잘 분리 된 느낌이 듭니다.
질문이 하나 있다면, 수정을 하고 보니 클래스가 몇 개 더 생겨, 구분을 지어 줘야할 것 같아 model 패키지 안에 framework라는 패키지를 만들었는데, 이에 대해 피드백 부탁드립니다 ! :)

좋은 피드백 감사합니다~!

2019-05-28 14:33 UTC, gracefulBrown commented on src/main/java/coordinate/model/Point.java
> +import java.util.Comparator;
Optimize Imports를 이용하여 사용하지 않는 import를 제거해보세요~

2019-05-28 14:33 UTC, gracefulBrown commented on src/main/java/coordinate/model/framework/PointsCreator.java
> +                                Matcher matcher = Pattern.compile(POINT_REGEX).matcher(input);
method 분리를 해보는건 어떨까요?

2019-05-28 14:33 UTC, gracefulBrown commented on src/main/java/coordinate/model/framework/IShape.java
> +public interface IShape {
인터페이스의 I를 prefix로 하는 네이밍을 헝가리안 표기법이라고 하는데요
클린코드에 헝가리안 표기법 관련 언급이 있네요ㅎㅎ 참고하시면 좋을 것 같아요 :)

### 참고 문서
- [헝가리안 표기법](https://ko.wikipedia.org/wiki/%ED%97%9D%EA%B0%80%EB%A6%AC%EC%95%88_%ED%91%9C%EA%B8%B0%EB%B2%95)
- [클린코드 > 2장 의미 있는 이름 > 인코딩을 피하라 > 헝가리식 표기법](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md#%EC%9D%B8%EC%BD%94%EB%94%A9%EC%9D%84-%ED%94%BC%ED%95%98%EB%9D%BC%EB%B3%80%EC%88%98%EC%97%90-%EB%B6%80%EA%B0%80-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EB%8D%A7%EB%B6%99%EC%97%AC-%ED%91%9C%EA%B8%B0%ED%95%98%EB%8A%94-%EA%B2%83%EC%9D%84-%EB%9C%BB%ED%95%A8)

2019-05-28 14:33 UTC, gracefulBrown commented on src/main/java/coordinate/view/OutputView.java
> +        private static void drawYAxis(StringBuilder sb, int index) {
삼항 연산자의 사용으로 인해 가독성이 떨어진다고 판단될 때는 메서드 분리를 해주시면 조금 도움이 될 것 같습니다 :)

2019-05-28 14:39 UTC, gracefulBrown commented
패키지를 나누는 시도 👍 
좋은 것 같습니다

추가적으로 참고하면 좋을 것 같은 문서가 있는데 
https://www.slipp.net/questions/36 에 보면 패키지를 어떻게 나누는게 좋은지에 대한 질문과 답변쓰레드가 있는데요
쿠기가 작업한 내용과 비교해보면
framework이라고 명명한 레이어별로 패키징을 할 지, 아니면 관련된 기능 분류로 하는 모듈별로 할 지에 대해 고민을 해보면 좋을 것 같아요.

2019-05-28 14:42 UTC, gracefulBrown approved these changes
피드백 반영을 잘 해주셨네요!! 💯 
몇 가지 도움이 될 만한 피드백 남겼으니 확인 한번 해보세요 :)
수고 많으셨습니다.

2019-05-28 14:42 UTC, merged