[좌표 계산기] 뚱이 미션 제출합니다.
woowacourse/java-coordinate pull request #18
Opened 2019-05-23 12:10 UTC by starkim06

많은 지적 해주시면 부탁드립니다.
감사합니다 ㅎㅎ

2019-05-27 23:57 UTC, woowahanCU commented on src/main/java/coordinate/CoordinateApp.java
> +    private static ShapeFactory shapeFactory = new ShapeFactory();
👍

2019-05-27 23:58 UTC, woowahanCU commented on src/main/java/coordinate/domain/ShapeFactory.java
> +    }
👍

2019-05-28 01:48 UTC, woowahanCU commented on src/main/java/coordinate/view/OutputView.java
> +    private static void printPoints(boolean[][] coordinates) {
이번 미션은 프로그래밍 요구사항이 인덴트 1까지만 허용입니다.

2019-05-28 01:48 UTC, woowahanCU commented on src/main/java/coordinate/view/OutputView.java
> +                if (coordinates[i][j]) {
프로그래밍 요구사항에 배열대신 ArrayList를 사용하라는 부분이 있어요

2019-05-28 01:49 UTC, woowahanCU commented on src/main/java/coordinate/view/OutputView.java
> +        for (int i = 0; i < 24; i++) {
값을 하드코딩하기 보다 이미 있는 상수를 활용해도 좋지 않을까요

2019-05-28 01:51 UTC, woowahanCU commented on src/test/java/coordinate/domain/RectangleTest.java
> +        assertThrows(IllegalArgumentException.class,()->{
공백 컨벤션 위반

2019-05-28 01:55 UTC, woowahanCU commented on src/main/java/coordinate/view/InputView.java
> +public class InputView {
Input 값검증에 대한 테스트도 필요할 거 같아요.

2019-05-28 05:23 UTC, woowahanCU commented on src/main/java/coordinate/domain/Point.java
> +    private final int x;
x, y도 공통적인 부분들이 보이는데요. 원시타입을 한번더 포장할 수 있지 않을까요

2019-05-28 05:30 UTC, woowahanCU commented on src/main/java/coordinate/domain/Rectangle.java
> +            map.put(side, map.getOrDefault(side, 0) + 1);
어떤 유효성을 체크하는 것인지 메소드 분리해서 명시적으로 나타내는게 좋을거 같아요

2019-05-28 05:56 UTC, woowahanCU commented on src/main/java/coordinate/domain/Shape.java
> +            for (int j = i + 1; j < points.size(); j++) {
이번 프로그래밍 요구사항은 인덴트 1까지 허용입니다.

2019-05-28 05:56 UTC, woowahanCU commented on src/main/java/coordinate/view/InputView.java
> +    public static List<Point> inputCoordinate() {
이번 프로그래밍 요구사항은 메소드라인 10줄까지 허용입니다.

2019-05-28 05:57 UTC, woowahanCU commented on src/main/java/coordinate/view/OutputView.java
> +        for (int i = 0; i < MAX_Y; i++) {
이번 미션은 프로그래밍 요구사항이 인덴트 1까지만 허용입니다.

2019-05-28 05:59 UTC, woowahanCU requested changes
안녕하세요. 리뷰어 CU입니다.
이번 미션 진행하면서 프리코스때부터 요구되었던, 프로그래밍 요구사항들이 다수 반영이 안되었네요.
수정 반영 후에 다시 리뷰요청 부탁드릴게요. 감사합니다.

2019-05-28 10:14 UTC, starkim06 commented on src/main/java/coordinate/view/OutputView.java
> +    private static void printPoints(boolean[][] coordinates) {
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:14 UTC, starkim06 commented on src/main/java/coordinate/view/OutputView.java
> +                if (coordinates[i][j]) {
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:14 UTC, starkim06 commented on src/main/java/coordinate/view/OutputView.java
> +        for (int i = 0; i < 24; i++) {
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:15 UTC, starkim06 commented on src/test/java/coordinate/domain/RectangleTest.java
> +        assertThrows(IllegalArgumentException.class,()->{
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:15 UTC, starkim06 commented on src/main/java/coordinate/view/InputView.java
> +public class InputView {
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:15 UTC, starkim06 commented on src/main/java/coordinate/domain/Point.java
> +    private final int x;
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:15 UTC, starkim06 commented on src/main/java/coordinate/domain/Rectangle.java
> +            map.put(side, map.getOrDefault(side, 0) + 1);
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:15 UTC, starkim06 commented on src/main/java/coordinate/domain/Shape.java
> +            for (int j = i + 1; j < points.size(); j++) {
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:15 UTC, starkim06 commented on src/main/java/coordinate/view/InputView.java
> +    public static List<Point> inputCoordinate() {
피드백 감사합니다.
반영 했습니다.

2019-05-28 10:15 UTC, starkim06 commented on src/main/java/coordinate/view/OutputView.java
> +        for (int i = 0; i < MAX_Y; i++) {
피드백 감사합니다.
반영 했습니다.

2019-05-28 14:32 UTC, woowahanCU commented on src/main/java/coordinate/domain/ShapeFactory.java
> +    }
enummap을 사용할 때와는 어떤 차이가 있을까요

2019-05-28 14:37 UTC, woowahanCU commented on src/main/java/coordinate/domain/Coordinate.java
> +    }
저는 innerclass, enum 등은 가장 밑에 구현하는 편입니다.
https://stackoverflow.com/questions/4730126/where-to-put-inner-classes

2019-05-28 14:43 UTC, woowahanCU commented on src/main/java/coordinate/domain/Shape.java
> +import java.util.ArrayList;
사용하지 않는 import 제거

2019-05-28 14:45 UTC, woowahanCU commented on src/main/java/coordinate/domain/PointsFactory.java
> +    private static void getPoint(List<Point> points, String input) {
Points 일급콜렉션을 생성했으니 이부분은 그쪽에 위임하는게 자연스러워 보이네요

2019-05-28 14:46 UTC, woowahanCU approved these changes
피드백 반영해주셔서 고맙습니다 👍 
몇가지 피드백 남겼으니 확인해보시구요. 궁금한 점 있으면 DM 남겨주세요
이번 미션은 여기서 Merge 할게요! 수고하셨어요~ ㅎㅎ

2019-05-28 14:47 UTC, merged