[좌표 계산기] 버디 미션 제출합니다.
woowacourse/java-coordinate pull request #29
Opened 2019-05-24 07:55 UTC by imkimheejoo

2019-05-25 13:21 UTC, jihan805 requested changes
안녕하세요 버디님! 
전체적인 설계, 테스트 코드 💯 
몇가지 피드백 남겼으니 확인 부탁드릴게요 :)

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/fuel/domain/Car.java
> +    abstract int getDistancePerLitter();
불필요한 공백은 제거해도 좋을 것 같아요!

추가로, 2단계 요구사항인 인터페이스를 적용해보면 어떨까요?

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/coordinate/view/InputView.java
> +    }
InputView 분리 👍 
하지만 InputView는 인풋을 받기 위한 용도로만 사용하면 더 좋을 것 같아요! (현재 두가지 역할을 하고 있어요)
Point 생성을 분리해보면 어떨까요?

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/coordinate/domain/FigureFactory.java
> +        return generateLine(pointList.getPoint(0), pointList.getPoint(1));
FigureFactory 클래스를 통해 도형 선택하도록 설계, 상수 사용 👍 
도형을 구분하기 위해 if문을 사용하지 않도록 고민해보면 어떨까요?
힌트 : map, enum  등을 사용하면 좋을 것 같아요!

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/coordinate/domain/Figure.java
> +
사용하지 않는 import는 제거하면 훨씬 깔끔해요!

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/coordinate/domain/PointList.java
> +    private final List<Point> points;
List<Point>에 대한 일급 콜렉션 적용 💯 
클래스 이름, 변수등에 자료구조를 나타내는 네이밍은 사용을 피하면 좋아요!
Points와 같이 변경하면 어떨까요?

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/coordinate/domain/PointList.java
> +        if (!(points.size() >= 2 && points.size() <= 4)) {
상수 활용!
코드 전체적으로 확인해보고 상수를 활용해보면 어떨까요?

2019-05-25 13:21 UTC, jihan805 commented on src/test/java/coordinate/FigureFactoryTest.java
> +    }
FigureFactory는 Point의 수에 맞는 적절한 도형을 반환해주는가에 대해 테스트 하는 것이 더 적절하지 않을까요?

2019-05-25 13:21 UTC, jihan805 commented on src/test/java/coordinate/TriangleTest.java
> +
전체적으로 테스트 코드를 꼼꼼하게 잘 구현하셨어요!
Line에 대한 테스트가 안보이는 것 같아요!

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/coordinate/domain/Line.java
> +
삼각형, 사각형의 Area를  구하는 것은 Line의 역할이 아닌 것 같아요!

2019-05-25 13:21 UTC, jihan805 commented on src/main/java/coordinate/domain/Line.java
> +
Double을 사용한 특별한 이유가 있을까요?

2019-05-26 14:49 UTC, jihan805 requested changes
안녕하세요 버디님!
전체적으로 피드백 반영 💯 👍 
몇가지 간단한 피드백 남겼으니 확인 부탁드릴게요 :)

2019-05-26 14:49 UTC, jihan805 commented on src/test/java/coordinate/domain/FigureFactoryTest.java
> +    }
하나의 테스트 메서드에는 assert문을 최소로 사용하도록 해요!
분리해보면 어떨까요?

여러개의 assert를 사용하면 어떤 문제가 발생할 수 있을까요?

2019-05-26 14:49 UTC, jihan805 commented on src/main/java/coordinate/domain/FigureFactory.java
> +        throw new IllegalArgumentException("만들 수 있는 도형이 없습니다.");
indent(인덴트, 들여쓰기) depth를 2단계에서 1단계로 줄여라!
고민해보면 어떨까요?

2019-05-26 14:49 UTC, jihan805 commented on src/main/java/coordinate/domain/Point.java
> +
원시값으로 포장해보면 어떨까요?

2019-05-26 14:49 UTC, jihan805 commented on src/main/java/coordinate/domain/Point.java
> +    }
상수 활용!

2019-05-26 14:49 UTC, jihan805 commented on src/main/java/coordinate/domain/Rectangle.java
> +    Rectangle(Points points) {
한줄 띄면 더 깔끔할것 같아요!

2019-05-26 14:49 UTC, jihan805 commented on src/main/java/coordinate/domain/Rectangle.java
> +        if (!(lines.get(index).equals(lines.get(index + 1)))) {
checkRectangle인 것 같아요!!

2019-05-26 14:49 UTC, jihan805 commented on src/main/java/coordinate/domain/Rectangle.java
> +        double depth = points.getPoint(FIRST_POINT).calculateLength(points.getPoint(THIRD_POINT));
points.getPoint(index) 대신 AbstractFigure에 getPoint(index) 라는 메서드를 만들어보면 어떨까요?

2019-05-26 14:49 UTC, jihan805 commented on src/test/java/coordinate/domain/PointTest.java
> +
경계값을 이용해 테스트 작성 💯

2019-05-27 06:39 UTC, imkimheejoo commented on src/test/java/coordinate/domain/FigureFactoryTest.java
> +    }
제가 찾아본 바로는 
하나의 테스트 메서드에서 예외를 확인할 때 여러개의 assert문을 사용하면 예외가 어느 것이 발생했는지 알지 못하기 때문에 문제가 발생한다고 이해했습니다..!
잘못알고 이해한거라면 다시 찾아보겠습니다!!

2019-05-29 12:07 UTC, jihan805 requested changes
안녕하세요 버디님, 피드백 반영 💯 
마지막으로 간단한 피드백 한가지 남겼으니 확인 부탁드릴게요!
감사합니다 :)

2019-05-29 12:07 UTC, jihan805 commented on src/main/java/coordinate/domain/Point.java
> +    }
space 컨벤션, 쉼표 뒤에 한칸 띄어써야 해요!

2019-05-29 12:07 UTC, jihan805 commented on src/test/java/coordinate/domain/PointTest.java
> +            new Point(25,1);
요기도 space 컨벤션 위반!
쉼표 근처 space 컨벤셔에 유의하면 좋을 것 같아요!

2019-05-29 12:07 UTC, jihan805 commented on src/main/java/coordinate/domain/Coordinate.java
> +
Coordinate 구현 👍 
지금 같은 구조이면, 매번 새로운 인스턴스가 생기게 되요!
재사용 가능한 구조로 변경해보면 어떨까요?
힌트 : map

마지막으로 재사용 가능한 구조로 변경하는 연습만 진행한 후 머지 할게요 ! :)

2019-05-29 12:39 UTC, jihan805 approved these changes
버디님, 엄청 빠르게 반영해주셨네요!
머지 진행할게요 :)

2019-05-29 12:39 UTC, jihan805 commented on src/main/java/coordinate/domain/Coordinate.java
> +        if (!coordinates.containsKey(coordinate)) {
getInstance와 같은 이름이 조금 더 적절할거같아요!

2019-05-29 12:39 UTC, merged