[좌표 계산기] 마틴 미션 제출합니다.
woowacourse/java-coordinate pull request #36
Opened 2019-05-25 07:27 UTC by oeeen

안녕하세요! 잘 부탁드립니다!

2019-05-26 03:53 UTC, kang-hyungu requested changes
안녕하세요 마틴님 리뷰어 강현구입니다
객체지향적으로 설계가 잘 되어 있네요 :+1: 
몇가지 간단한 피드백 남겼으니 확인해보시고 적용해보아요~!
완료되면 리뷰 요청주세요!

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/Drawer.java
> +    public static Drawer newInstance(Points points) {
팩토리 메서드를 만든 이유가 있을까요?
생성자랑 하는 일이 달라보이지 않네요

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/Drawer.java
> +            board.get(COORDINATE_UPPER_BOUND - point.getY()).replace(point.getX() * COORDINATE_Y_OFFSET + COORDINATE_X_OFFSET, point.getX() * COORDINATE_Y_OFFSET + COORDINATE_X_OFFSET + 1, "*");
replace를 어떤 값에서 어떤 값으로 했는지 변수로 보여주면 어떨까요?
한줄에 너무 많은 계산식이 들어가면 코드 읽기가 힘들어요

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/Line.java
> +        return sb.append(calculateResult()).toString();
```suggestion
        return return LINE_RESULT_MESSAGE + calculateResult();
```
성능이 문제가 되지 않는다면 더 간결하게 가는건 어떨까요?

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/NumberOfPoints.java
> +public enum NumberOfPoints {
:+1:

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/Rectangle.java
> +        if (!(sortedPoints.get(1).getX() == sortedPoints.get(0).getX() && sortedPoints.get(3).getX() == sortedPoints.get(2).getX() && sortedPoints.get(2).getY() == sortedPoints.get(0).getY() && sorte
한 줄에 너무 많은 코드가 들어가서 읽기 힘드네요..
변수로 빼거나 메서드로 추출해보아요
구글 자바 스타일 가이드에서는 100자로 제한하는데 이건 협업할 때 사람들이랑 이야기해서 조절하면 될거에요.
https://google.github.io/styleguide/javaguide.html#s4.4-column-limit

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/parent/Figure.java
> +    String makeResult();
view 계층에 해당되는 로직 같은데 인터페이스가 가지고 있는게 맞을까요?
웹이나 모바일 환경이 추가된다면 모든 구현 객체에 필요한 기능이 아닐 것 같네요

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/Triangle.java
> +        Point point1 = sortedPoints.get(0);
1, 2, 3보다 좀더 의미를 잘 표현할 수 있는 변수명 없을까요?

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/util/AxisValidator.java
> +public class AxisValidator {
패키지 위치를 util이 아닌 validator를 만들거나 domain에 두는게 어떨까요

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/util/PointsGenerator.java
> +public class PointsGenerator {
도메인 클래스니 util 패키지가 어울리지 않네요

2019-05-26 03:53 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/view/OutputView.java
> +        for (int i = 0; i < board.size(); i++) {
ide가 foreach문을 제안하네요

2019-05-26 07:21 UTC, oeeen commented on src/main/java/coordinatecalculator/domain/Drawer.java
> +    public static Drawer newInstance(Points points) {
팩토리 메서드를 사용하면 유지보수에 용이해 진다고 해서 사용해보았습니만.. 현재 코드에서는 points에 따라 다른 성격의 객체를 생성하지 않기 때문에 굳이 팩토리 메서드로 만들지 않고 생성자에서만 해도 될 것 같네요. 
그래서 팩토리 메서드를 없애고 생성자를 public으로 변경하였습니다.

2019-05-26 07:21 UTC, oeeen commented on src/main/java/coordinatecalculator/domain/Drawer.java
> +            board.get(COORDINATE_UPPER_BOUND - point.getY()).replace(point.getX() * COORDINATE_Y_OFFSET + COORDINATE_X_OFFSET, point.getX() * COORDINATE_Y_OFFSET + COORDINATE_X_OFFSET + 1, "*");
변수를 추가하기 싫어서 한줄에 쭉 쓰다보니 너무 길어져서 가독성이 떨어진 것 같습니다.
replace를 board에서 y Index에 맞게 가져와서, x Index 위치에 있는 값을 변경 하는 것을 알 수 있도록 변수 추가 했습니다.

2019-05-26 07:22 UTC, oeeen commented on src/main/java/coordinatecalculator/domain/Line.java
> +        return sb.append(calculateResult()).toString();
추천해주신 코드로 변경했습니다. 추천해주신 코드가 객체 생성이 적어서 더 좋은 것 같습니다.

2019-05-26 07:49 UTC, oeeen commented on src/main/java/coordinatecalculator/domain/Rectangle.java
> +        if (!(sortedPoints.get(1).getX() == sortedPoints.get(0).getX() && sortedPoints.get(3).getX() == sortedPoints.get(2).getX() && sortedPoints.get(2).getY() == sortedPoints.get(0).getY() && sorte
변수로도 빼고 메서드로도 추출했는데, 메서드의 파라미터를 최소한으로 줄여보려고 수정하다보니 반복되는 코드들이 좀 생기게 된 것 같습니다. 조금 더 생각해 보도록 하겠습니다.

2019-05-26 13:43 UTC, oeeen commented on src/main/java/coordinatecalculator/domain/parent/Figure.java
> +    String makeResult();
Figure 인터페이스에서 따로 Console 이라는 인터페이스를 만들었는데 이렇게 하니 OutputView에서`((Console)figure).makeResult()` 이런 캐스팅이 생기는데, 이렇게 사용해도 되는 것인지 궁금합니다.

2019-05-27 14:21 UTC, kang-hyungu commented on src/main/java/coordinatecalculator/domain/parent/Figure.java
> +    String makeResult();
Console 인터페이스를 추가해서 콘솔 출력하는 구조도 웹, 모바일 추가될 때마다 새로운 인터페이스를 추가해야되지 않을까요?
뷰 계층에 타입에 따라 메시지 다르게 나오는 로직을 넣기에는 작은 프로그램이니 mvc 모델 학습할 때 더 고민해보도록 해보아요

2019-05-27 14:27 UTC, kang-hyungu approved these changes
피드백 반영 잘 되었네요 :+1: 
질문 주신 내용에 코멘트 남겼어요.
적용하신 방법도 나쁘진 않아요.
다만 딱 뭐가 정답이라고 말하기 애매한 부분이 있네요. 코멘트는 참고만 하세요.
코드 구현하느라 수고하셨습니다!

2019-05-27 14:27 UTC, merged