[좌표 계산기] 코나스 미션 제출합니다.
woowacourse/java-coordinate pull request #37
Opened 2019-05-25 15:13 UTC by Conatuseus

안녕하세요.
많은 지적 부탁드릴게요!!

2019-05-26 06:34 UTC, Conatuseus commented
질문있습니다.
오늘 클린 코드 책을 읽기 시작하면서 생각난 질문인데요.

1. 클래스 네이밍 문제
  제 클래스를 보시면 XPoint, YPoint 이런식으로 있는데
  (같이 쓰이는 이름) + (분류이름) ->  PointX , PointY 
  (분류 이름) + (같은 쓰이는 이름) -> XPoint, YPoint
 이 둘중에 어떤 것이 좋은지 궁금해요.

 2. 메소드를 따로 만들어 쓰는 것에 대한 문제
  예를들면) Points 클래스에서 List<Point> points가 있는데요.
  외부에서 points에 접근할 때   points.getPoints().get(i).~~~  이런식으로 막 길어지면 가독성이 떨어진다고 생각해서
  getPointByIndex(int index)  이런식으로 만들어서 자주 쓰곤 해요
 이렇게 만들어 쓰는 것에 대해 어떻게 생각하시나요?

2019-05-26 09:31 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 인터페이스, 추상 클래스 활용 잘하신 것 같아요. 👍 
질문사항 답이랑 피드백 몇가지 추가했어요. 
참고해주시고 궁금하신 점 있으시면 연락주세요. :)

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/controller/CoordinateController.java
> +            FigureCreator figureCreator=new FigureFactory();
= 좌우 공백이 안들어간것같아요. :)

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/XPoint.java
> +public class XPoint extends PointProperties {
XPoint와  YPoint를 분리한 이유를 할 수 있을까요?
두개의 객체가 완벽히 같은 역할을 하고 있는것 같아요. :)
0부터 25까지의 숫자를 표현하는 Point의 하나의 Coordinate라는 클래스로 표현하면 될 것 같아서요. :)
X축, Y축에 대한건 Point의 필드 이름으로만 구분지어도 될 것 같습니다.

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/rentcompany/Car.java
> +public abstract class Car implements ICar {
요새는 인터페이스의 접두사로 I를 붙이지 않고 있어요. :)
현재 인터페이스로 표현하고자하는 Car의 속성을 형용사형으로 표현하거나 그냥 Car라 하시면 될 것 같아요. :)

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Triangle.java
> +        final double pythagorean = firstLength * firstLength + secondLength * secondLength - thirdLength * thirdLength;
연산자로만 나열되어있다보니 코드가 많이 눈에 안들어 오는 것 같아요. :) Math를 사용해서 구분해보면 어떨까요?

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Triangle.java
> +        return "삼각형의 넓이는 " + getArea();
`이펙티브 자바 규칙 10 - toString은 항상 재정의하자`
해당 부분 참고해주세요.
toString은 해당 객체의 상태를 바로 알 수 있는 의미있는 값으로 표현이 되야해요. :)
해당 toString은 이 객체의 상태를 너비 외에는 전혀 담고 있지 못한 것 같아요.
뷰를 로직이라면 별도 메서드로 빼거나 책임을 분리하는게 좋을 것 같습니다. :)

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Points.java
> +    private List<Point> points;
일급 컬렉션 👍 
final로 선언하는게 더 안전하지 않을까요?

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Points.java
> +        return points;
외부에 컬렉션을 제공할 때는 Collections.unmodifiableList로 감싸서 전달하는게 더 안전할 것 같습니다. :)

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Points.java
> +    public Point getPoint(int index) {
말씀하신대로 인덱스를 전달받아서 실제 원소를 돌려주는것도 좋은 방법으로 보여요. :)

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Points.java
> +    public List<Distance> generateDistances() {
Points를 생성할 때 각 Point들에 대한 순서보장이 되나요?
각 점이 어떤 점에 대한 Distance인지 드러나지 않을 것 같아서요. :)
기능만 제공하고 직접 점들을 이용해 거리를 구하는게 명확하지 않을까요?

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Points.java
> +        return new Distance(this.getPoint(previousPointIndex), this.getPoint(currentPointIndex));
Point와 Point간의 메서드로 Distance를 돌려주도록 하면 어떨까요?

2019-05-26 09:31 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Line.java
> +    private double distance;
Distance라는 포장클래스도 생성했는데 그걸 사용하면 어떨까요?
그리고 현재 distnace라는 필드 만으로는 Line의 상태를 제대로 표현해주지 못하고 있는 것 같아요.
다른 도형과 마찬가지로 어떤 Point에 대해서 관심을 가져야하지 않을까요?

2019-05-27 05:00 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/XPoint.java
> +public class XPoint extends PointProperties {
처음에 설계할 때,  나중에는 X와 Y가 다른 역할을 할 수도 있겠다는 생각에
분리해서 짰어요.
나중에 두 개가 완벽히 같은 역할을 하는 것을 알았지만, 분리하는게 더 낫지 않을까라는 생각에 합치지 않고 분리해놨었어요 😄

2019-05-27 05:01 UTC, Conatuseus commented on src/main/java/rentcompany/Car.java
> +public abstract class Car implements ICar {
Car 클래스는 CarImpl 로,   인터페이스 ICar 는 Car로 변경했습니다 👍

2019-05-27 05:17 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Triangle.java
> +        final double pythagorean = firstLength * firstLength + secondLength * secondLength - thirdLength * thirdLength;
Math의 pow를 사용해서 변경했습니다! 😃

2019-05-27 05:22 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Points.java
> +        return points;
처음 알게된 메소드네요.
감사합니다!

2019-05-27 05:36 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Points.java
> +    public Point getPoint(int index) {
넵 감사합니다.
메소드명이 getter와 헷갈릴 수 있어서 getPointByIndex로 수정했습니다.

2019-05-27 05:37 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Points.java
> +    private List<Point> points;
감사합니다 :D

2019-05-27 06:09 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Line.java
> +    private double distance;
Distance 포장클래스를 사용하도록 변경했습니다.
하지만 
화투님의 "다른 도형과 마찬가지로 어떤 Point에 대해서 관심을 가져야하지 않을까요?"
이 말씀을 제대로 이해했는지 모르겠네요.

2019-05-27 06:09 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Points.java
> +        return new Distance(this.getPoint(previousPointIndex), this.getPoint(currentPointIndex));
네 그렇게 하도록 수정했습니다.!

2019-05-27 06:30 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Points.java
> +    public List<Distance> generateDistances() {
이 메소드는 삼각형 넓이를 구할 때
**모든 선분의 길이를 알아야 되서 만든 메소드**에요.

사각형은 직사각형의  대각선 점 2개를 구해서
x의 차이 * y의 차이 로 넓이를 구했어요.

( 제가 Rectangle에서 이 메소드를 사용하는 줄 착각하고 
points를 sorting하기 위해 Comparable을 구현했네요...)

2019-05-27 06:30 UTC, Conatuseus commented on src/main/java/coordinatecalculator/controller/CoordinateController.java
> +            FigureCreator figureCreator=new FigureFactory();
확인했습니다 😄

2019-05-27 06:39 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Triangle.java
> +        return "삼각형의 넓이는 " + getArea();
toString 메소드를 의미있는 값으로 표현되도록 모두 변경했고,
뷰로 출력하기 위해 Figure 인터페이스에 새로운 메소드를 만들어서
각각 출력할 내용을 반환하도록 했어요.
OutputView에서는 Figure 객체를 받아서 위의 메소드를 실행한 결과를 출력하도록 했습니다.

만약 책임을 분리한다면 어떻게 해야할까요?

2019-05-27 06:39 UTC, Conatuseus commented
피드백 반영해서 리팩토링 했고,
댓글로 질문들 남겼습니다 확인부탁드려요.

2019-05-27 08:18 UTC, Conatuseus commented
> 피드백 반영해서 리팩토링 했고,
> 댓글로 질문들 남겼습니다 확인부탁드려요.
>

2019-05-27 12:30 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다. :) 
피드백 반영해주셔서 감사합니다. 구현 너무 잘하셨어요. :)
질문에 대한 답과 피드백 몇가지 추가했어요. 참고 부탁드릴게요!

2019-05-27 12:30 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Triangle.java
> +        return "삼각형의 넓이는 " + getArea();
방법은 여러개가 있을 것 같아요.
1. FigureFactory처럼 별도 map이나 enum을 통해서 출력 문자열을 생성하는 방법.
2. Visitor 패턴을 활용해 출력을 생성하는 방법. (다만 이 경우에는 출력에 대한 인터페이스는 가져가겠네요.)

그 외에도 다양한 방법이 있을 것 같은데요. :) 고민해보시면 좋을 것 같아요.

2019-05-27 12:30 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Point.java
> +    public Point(String inputPoint) {
Matcher를 통해 문자열을 파싱하는 역할은 Point의 관심사가 아닌 것 같아요. :)
다른곳으로 관심사를 분리해보면 어떨까요?

2019-05-27 12:30 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Point.java
> +    public double getSlope(Point point) {
getSlope, getDistance등 getter는 내부 필드의 값을 구할 때 관례적으로 사용하는 이름이에요!
조금 더 명확하게 표현하면 좋을 것 같아요. :)

2019-05-27 12:30 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/Point.java
> +        if (xPoint.equals(o.xPoint)) {
coordinate 또한 Comparable를 구현해서 표현해보면 어떨까요?

2019-05-27 12:31 UTC, phs1116 commented
> 피드백 감사드립니다 😄 👍
> 피드백 반영해서 리팩토링 했고,
> 댓글로 질문들 남겼습니다 확인부탁드려요.
> 추가로 도메인의 패키지를 좀 더 깔끔하게 나누고싶은데,
> 어떤 글을 보면 잘 알 수 있을까요?

> 피드백 감사드립니다 😄 👍
> 피드백 반영해서 리팩토링 했고,
> 댓글로 질문들 남겼습니다 확인부탁드려요.
> 추가로 도메인의 패키지를 좀 더 깔끔하게 나누고싶은데,
> 어떤 글을 보면 잘 알 수 있을까요?

패키지에 대한 부분은 사실 회사마다 팀마다 항상 다른 부분이라서 뭐가 정답이다!
라고 할만한 글이 없기는 해요!
다만 1차적으로는 계층별로 구분을 하고(프레젠테이션(뷰), 어플리케이션, 도메인), 
그 내부적으로는 관심사별로 분리를 하기도 하고요.
글은 아니지만 DDD 관련해서 공부해보시면 어떤식으로 관심사와 패키지를 쪼개는지 잘 아실수 있을것 같네요. :)
책도 많으니 참고해보세요!

2019-05-27 13:22 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Point.java
> +    public Point(String inputPoint) {
파싱하는 부분을 View에서 할 것인지, Paser같은 클래스를 만들어서(예를들면 PointPaser) 할 지
선택적인가요? 아니면 무엇이 더 괜찮다 라는게 있을까요?

2019-05-27 13:26 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Point.java
> +    public double getSlope(Point point) {
아무 생각없이 get 을 써버렸네요ㅎㅎ
감사합니다! 👍

2019-05-27 13:27 UTC, Conatuseus commented on src/main/java/coordinatecalculator/model/Point.java
> +        if (xPoint.equals(o.xPoint)) {
Coordinate에서 Comparable을 구현해서 사용하도록 변경했습니다. 😃

2019-06-01 08:21 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다. :)
피드백 잘 반영해주셔서 감사합니다.
이번 단계 머지할게요! 
개발하시느라 수고 많으셨습니다! :)

2019-06-01 08:21 UTC, phs1116 commented on src/main/java/coordinatecalculator/model/FigureFactory.java
> +    private static final int LINE_SIZE = 2;
LineSize등 각 객체의 특성들은  Factory가 아니라 각 클래스에서 관리하는게 더 적합하지 않을까요? :)

2019-06-01 08:21 UTC, merged