[좌표계산기] 러너덕 미션 제출합니다
woowacourse/java-coordinate pull request #48
Opened 2019-05-27 12:13 UTC by Deocksoo

2019-05-30 07:09 UTC, gracefulBrown requested changes
안녕하세요. 리뷰어 브라운입니다 :)
코드를 깔끔하게 잘 구현하셨네요 👍 
몇 가지 코멘트를 남겼으니 참고해서 구현해보면 좋을 것 같아요 ^^
궁금한 점 있으시면 편하게 DM 주세요~

2019-05-30 07:09 UTC, gracefulBrown commented on src/main/java/coordinate/domain/PointParser.java
> +    public static List<Point> parse(String rawInput) {
Point들과 관련된 기능들을 모아서 일급 컬렉션 객체를 만드는건 어떨까요? :)

2019-05-30 07:09 UTC, gracefulBrown commented on src/main/java/coordinate/domain/Figure.java
> +public abstract class Figure {
좌표계산기 5단계 - 인터페이스 적용 은 포함이 안된 것 같아요ㅠㅠ

2019-05-30 07:09 UTC, gracefulBrown commented on src/main/java/coordinate/domain/FigureCreator.java
> +public class FigureCreator {
혹시 FigureFactory와 Creator를 구분한 이유가 있을까요?

2019-05-30 07:09 UTC, gracefulBrown commented on src/main/java/coordinate/domain/Point.java
> +    int getDeltaXTo(Point point) {
수식 메서드 분리👍

2019-05-30 07:09 UTC, gracefulBrown commented on src/main/java/coordinate/domain/StraightLine.java
> +    private void validateSizeOf(List<Point> points) {
모든 도형에서 validation을 하는데
추상클래스에서 추상메소드로 만든 후 추상클래스의 생성자에서 호출하도록 하면 어떨까요?

각 도형의 생성자부분의 중복을 줄일 수 있을 것 같아요 :)

2019-05-30 07:09 UTC, gracefulBrown commented on src/main/java/coordinate/domain/AreaType.java
> +public enum AreaType {
enum으로 타입구분 👍

2019-06-03 08:37 UTC, Deocksoo commented
안녕하세요 브라운, 피드백 남겨주신부분 모두 수정해보았습니다! 

1.  FigureFactory와 Creator를 구분했던 이유는 Factory에서는 각 Figure의 Creator에 대한 mapping만 담당하고, 실제 Figure의 제작은 Creator에서 하도록 하기 위해서였습니다. 그런데 생각해보니 조금 이상했어요. Factory가 Figure를 만들도록 하는 게 더 자연스러울 것 같았습니다. Creator 클래스를 굳이 구분하지 않고 Interface로 만들어 익명 함수로 구현하면 보다 간결하게 구현할 수 있을것도 같았구요. 그래서 일단 생각나는대로 구현하기는 하였는데, 의도하신 방향에 맞았는지 잘 모르겠습니다. 
2.  point들의 list를 일급 콜렉션으로 한번 더 감싸는 것도 시도해보았습니다. 생각보다 수정해야할 부분이 많아서 깔끔하게 잘 되지는 않은 것 같아요ㅜㅜ parser를 없애고 point와 관련된 기능을 모두 담당하도록 하였는데, 혹시 너무 많은 기능을 담당하고 있지는 않은가요? 

추가로 수정해야할 부분이 있으면 또 말씀해주세요! 
신경써 리뷰해주셔서 감사합니다 :)

2019-06-06 04:04 UTC, gracefulBrown approved these changes
피드백 반영 잘 해주셨습니다! 👍 
질문주신 부분 중 1번은 잘 리팩토링 된 것 같고 2번은 코멘트로 남겼습니다.
고생 많으셨습니다 :)

2019-06-06 04:04 UTC, gracefulBrown commented on src/main/java/coordinate/domain/Points.java
> +    private static List<Point> parse(String rawInput) {
일급컬렉션 구현 👍 피드백 반영 잘 해주셨어요.
이렇게 구현하고 보니 해당 로직은 뷰에 종속적일 수 있겠다는 생각이 드네요
예를들면 콘솔에서는 String을 파싱에서 값을 받았지만 웹에서는 값들을 각각 입력받을 수 있을 것 같아서요..

입력뷰에 종속적이지 않게하는 방법을 한번 생각해보는것도 좋을 것 같아요 :)

2019-06-06 04:04 UTC, merged