[좌표 계산기] 루피 미션 제출합니다.
woowacourse/java-coordinate pull request #53
Opened 2019-06-18 15:29 UTC by MrKwon

안녕하세요. 루피입니다.
예비군으로 미루기 시작하여 다음 미션과 다른 프로젝트 진행하다가 이제서야 첫 리뷰 요청을 보내게 되었습니다.
좌표계산기에서 목표로 하는 부분인 인터페이스와 상속에 대하여 신경써서 구현해 보았습니다.
콘솔 UI 에서 좌표를 찍어주는 부분은 중요한 부분이 아니라고 하셔서
단순히 길이와 넓이를 구해서 출력해주도록 구성하였습니다.
감사합니다.

2019-06-21 14:17 UTC, kang-hyungu requested changes
안녕하세요 루피님 리뷰어 강현구입니다.
전체적으로 객체 설계도 좋고 코드 구현도 좋습니다 :100: 
관련해서 특별히 수정해야될 부분은 없어 보여요.
보강했으면 하는 부분은 테스트 코드입니다.
특히 Delta, Vector, DuplicateChecker 테스트도 추가해보아요
로직에서 중요한 기능을 하는 클래스인데 테스트가 없으면 변경에 취약해져요
확인해보시고 궁금한 사항 생기면 연락주세요~!

2019-06-21 14:17 UTC, kang-hyungu commented on src/main/java/com/woowa/coordinate/domain/Point.java
> +    public static Point of(String commaSeparated) {
유효성 검사는 해주는게 좋지 않을까요?

2019-06-21 14:17 UTC, kang-hyungu commented on src/main/java/com/woowa/coordinate/domain/figure/AbstractFigure.java
> +    public abstract int size();
size 메서드 결과를 points의 size()를 호출하게 만들면 선, 삼각형, 사각형 등 각 도형에서 하드코딩한 size 메서드 결과를 반환하지 않아도 될 것 같네요

2019-06-21 14:17 UTC, kang-hyungu commented on src/main/java/com/woowa/coordinate/domain/figure/Rectangle.java
> +        return Vector.get(points, START_POINT, 1)
객체지향 생활체조에 나오는 규칙 입니다.
규칙 4: 한 줄에 점을 하나만 찍는다.
Vector.get 할 때 어떤 값을 꺼내온건지 변수로 표현해주면 코드는 길어지지만 읽기 좋은 코드가 될거에요

2019-06-21 14:17 UTC, kang-hyungu commented on src/main/java/com/woowa/coordinate/domain/figure/Triangle.java
> +        if (Vector.get(points, 0, 1)
한줄에 너무 많은 내용을 넣지 말고 변수에 담아서 표현해주는 것도 좋을 것 같아요

2019-06-21 14:17 UTC, kang-hyungu commented on src/test/java/com/woowa/coordinate/domain/LineTest.java
> +    void generate_line() {
point가 2개 일 때 Line 객체가 생성되는 테스트와 넓이 계산이 의도한 대로 동작하는지 테스트하는 케이스 2가지로 나눠보아요

2019-06-21 14:17 UTC, kang-hyungu commented on src/test/java/com/woowa/coordinate/domain/PointTest.java
> +public class PointTest {
Point 클래스에서 각 생성자에 대한 테스트, subtractX, distance 같은 기능에 대한 테스트를 추가해보아요

2019-06-21 14:17 UTC, kang-hyungu commented on src/test/java/com/woowa/coordinate/domain/PointsTest.java
> +    void sortPoints_0() {
워우... 무슨 테스트일까요?

2019-06-21 14:17 UTC, kang-hyungu commented on src/test/java/com/woowa/coordinate/domain/RectangleTest.java
> +    void area() {
테스트 메서드명도 신경써서 작성해야합니다.
나중에 몇 개월 지나서 보면 무슨 테스트인지 기억 안나요
어떤 케이스를 테스트하고 싶었는지 한글로 작성해도 좋아요

2019-06-21 17:43 UTC, MrKwon commented on src/main/java/com/woowa/coordinate/domain/Point.java
> +    public static Point of(String commaSeparated) {
String 을 parameter 로 가지는 of 메서드에 대해서 유효성 검사는 총 2단계로 진행됩니다.

먼저, InputParser 에서
String 이 input 으로 들어올 때의 형식 검사와 동시에 (x,y)의 형식인지와 x와 y에 숫자가 들어가는지 검사합니다.

두번째로 Coordinate 의 생성자에서
coordinate 의 범위를 검증하는 로직이 존재합니다.

이런 경우에도 나중이나 다른 사람이 이 메서드를 사용하는 경우를 대비하여 따로 유효성 검사를 하는 것이 좋은지 여쭤보고 싶습니다.

이 피드백은 다시 리뷰 요청할 때는 일단 보류하도록 하겠습니다 !

2019-06-21 18:03 UTC, MrKwon commented on src/main/java/com/woowa/coordinate/domain/figure/AbstractFigure.java
> +    public abstract int size();
해당 클래스의 생성자에서 유효성을 검증하는 로직에서
하드코딩한 size 메서드 결과를 이용하고 있는데,
이 부분을 변경하면 유효성 검증 로직에서 NPE 를 throw 하면서 동작하지 않았습니다.

왜인지 곰곰히 생각해 보았습니다.
하드 코딩한 값을 이용해서 size 메서드를 구현한 이유는 각 도형에 필요한 점들의 수(하드코딩한 size 메서드 결과)를 기준으로 삼아 어떤 도형인지 검증하기 위함인데
points 의 size 를 반환하게 되면 input으로 들어온 point 의 수가 각 도형의 기준이 되는 논리적으로 불가능한 상황이 발생하게 되는 것으로 결론을 내려 필요하다고 생각했습니다.

혹시 저의 사고 과정에 오류가 있다면 다음 리뷰 요청에서 답변 달아주시면 감사하겠습니다.

2019-06-21 18:16 UTC, MrKwon commented on src/main/java/com/woowa/coordinate/domain/figure/Rectangle.java
> +        return Vector.get(points, START_POINT, 1)
피드백 반영하였습니다 !

2019-06-21 18:16 UTC, MrKwon commented on src/main/java/com/woowa/coordinate/domain/figure/Triangle.java
> +        if (Vector.get(points, 0, 1)
객체지향 생활체조에 나오는 규칙 입니다.
규칙 4: 한 줄에 점을 하나만 찍는다.

이 부분과 같은 맥락의 코멘트인 것 같아 반영하였습니다 !

2019-06-21 18:19 UTC, MrKwon commented on src/test/java/com/woowa/coordinate/domain/LineTest.java
> +    void generate_line() {
두 가지 테스트를 하나의 테스트 메서드로 진행하여 두개로 나눴습니다 !

감사합니다 !

2019-06-21 18:23 UTC, MrKwon commented on src/test/java/com/woowa/coordinate/domain/PointsTest.java
> +    void sortPoints_0() {
sortPoints 가 의도한대로 정렬이 되는지 확인하려는 의도에서의 테스트 였습니다.
하지만, 불필요하게 분리되어 있다고 판단하여 모든 테스트를 합쳤고
테스트 메서드 이름도 테스트 의도를 확인할 수 있도록 변경하였습니다 !

2019-06-21 18:26 UTC, MrKwon commented on src/test/java/com/woowa/coordinate/domain/RectangleTest.java
> +    void area() {
테스트 이름을 모두 한글로 바꾸고 어떤 의도인지 명확히 드러나도록 변경하였습니다 !

2019-06-23 11:03 UTC, MrKwon commented on src/test/java/com/woowa/coordinate/domain/PointTest.java
> +public class PointTest {
넵 ! 테스트 추가하였습니다 !

2019-06-24 07:15 UTC, MrKwon commented
안녕하세요. 현구님 리뷰이 루피입니다 ! 😄
귀한 시간 내주셔 피드백 해주신 점 감사드립니다.
조급하게 미션을 진행하다보니 테스트 코드가 부실 했던 점 피드백을 통해 보완하였습니다.
다만 몇 가지 궁금증이 생긴 피드백에 대해서는 코멘트를 남겨두었습니다 !
감사합니다 !

2019-06-25 12:05 UTC, kang-hyungu commented on src/main/java/com/woowa/coordinate/domain/Point.java
> +    public static Point of(String commaSeparated) {
1. InputParser처럼 사용자가 입력한 필수 값과 값의 형식에 대한 검사는 표현 영역에서 처리하는게 사용자 입장에서 좋습니다. 매 조건마다 exception 걸리는 것보다 한 번에 입력 받은 값들을 무엇무엇이 잘못되었는지 보여주는게 나을테니깐요. 스프링 mvc에서는 Validator 인터페이스를 제공해서 이런 문제를 해결하고 있습니다.
2. 객체 생성에 필요한 값 검증은 객체별 생성자에서 해주는게 안전합니다. 로직을 보면 최종적으로는 Coordinate 객체를 생성하게 되서 검증 로직을 다 타서 문제는 없겠지만요. 아니면 Point에서 문자열을 인자로 받는게 아니라 Coordinate으로 받으면 Point 로직 타기 전에 유효성 검증 먼저 가능하겠네요

2019-06-25 12:16 UTC, kang-hyungu commented on src/main/java/com/woowa/coordinate/domain/figure/AbstractFigure.java
> +    public abstract int size();
AbstractFigure 생성자에서 유효성 검사를 하면 size() 메서드가 abstract로 아직 정의가 안된 상태라 null이 발생할거에요.
유효성 검사는 상속 받은 클래스에서 처리하는게 좋겠네요. 각 클래스마다 유효성 검사 조건이 다를 수 있으니까요.
AbstractFigure의 size() 메서드를 abstract로 정의할 필요 없이 어차피 points 갯수니까 다 동일한 로직인데 하드코딩되어 있어서 남긴 코멘트였어요.
각 점의 갯수를 체크할 필요가 있다고 판단하면 그대로 가도 문제는 없어 보이네요

2019-06-25 12:18 UTC, kang-hyungu approved these changes
피드백 반영하신 부분 확인했습니다!
테스트가 촘촘해져서 리뷰하기도 수월하네요 :+1: 
구현하느라 고생하셨어요~!

2019-06-25 12:18 UTC, merged